<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Core/Matrix.fs" />
        <Compile Include="Core/Activation.fs" />
        <Compile Include="Losses.fs" />
        <Compile Include="Layers.fs" />
        <Compile Include="Optimizers.fs" />
        <Compile Include="Data.fs" />
        <Compile Include="Trainer.fs" />
        <Compile Include="ConvLayers.fs" />
        <Compile Include="TrainerCNN.fs" />
        <Compile Include="Experiments.fs" />
        <Compile Include="Examples/Iris.fs" />
        <Compile Include="Examples/MNIST.fs" />
        <Compile Include="Examples/CNNMNIST.fs" />
        <Compile Include="Examples/HyperparameterLab.fs" />
        <Compile Include="Examples/RegularizationMNIST.fs" />
        <Compile Include="Examples/Interpretability.fs" />
        <Compile Include="Examples/BenchmarkHarness.fs" />
        <Compile Include="Examples\Tests.fs" />
        <Content Include="Examples\Data\Iris.csv" />
        <Content Include="Examples\Data\mnist_test.csv" />
        <Content Include="Examples\Data\mnist_train.csv" />
        <Compile Include="Examples\TicTacToe.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

</Project>
